
# Contented database config

development:
  adapter: postgresql
  database: contented_development
  username: contented
  password: "M394P455W0Rd!!!"
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

test: &TEST
  adapter: postgresql
  database: contented_test
  username: contented
  password: "M394P455W0Rd!!!"
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

cucumber:
 <<: *TEST

production:
  adapter: postgresql
  database: contented_production
  username: contented
  password: "M394P455W0Rd!!!"
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000
